### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by wangchangyi1160** [LingYeAI/AdderNetCUDA#1]
hello, I run your code and there is an CUDA ERROR: an illegal memory access was encountered. The detailed information is 

Traceback (most recent call last):
  File "/home/new/classification-CNN/AdderNetCUDA-main/main.py", line 145, in <module>
    main()
  File "/home/new/classification-CNN/AdderNetCUDA-main/main.py", line 141, in main
    train_and_test(e)
  File "/home/new/classification-CNN/AdderNetCUDA-main/main.py", line 134, in train_and_test
    train(epoch)
  File "/home/new/classification-CNN/AdderNetCUDA-main/main.py", line 101, in train
    loss.backward()
  File "/home/new/anaconda3/envs/pytorch38/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/new/anaconda3/envs/pytorch38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
  File "/home/new/anaconda3/envs/pytorch38/lib/python3.8/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/new/classification-CNN/AdderNetCUDA-main/adder.py", line 78, in backward
    grad_W_col = grad_W_col/grad_W_col.norm(p=2).clamp(min=1e-12)*math.sqrt(W_col.size(1)*W_col.size(0))/5
  File "/home/new/anaconda3/envs/pytorch38/lib/python3.8/site-packages/torch/tensor.py", line 401, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "/home/new/anaconda3/envs/pytorch38/lib/python3.8/site-packages/torch/functional.py", line 1376, in norm
    return _VF.norm(input, p, dim=_dim, keepdim=keepdim)  # type: ignore
RuntimeError: CUDA error: an illegal memory access was encountered

Can you provide me with some solutions to this problem？

**Comment by LingYeAI** [comment]
Try use single GPU.
